version: 0.1

phases:
  pre_build:
    commands:
      - echo "Installing Mustache Globally"
      - npm install -g mustache

      - echo "Installing Project Dependencies..."
      - npm install

      - echo "Creating artifacts directory"
      - mkdir artifacts

      - echo "Creating AWS Config file"
      - 'echo "{ \"Region\": \"$AWS_REGION\", \"AccountId\": \"$AWS_ACCOUNT_ID\" }" > aws.json'

  build:
    commands:
      - echo "Running lint..."
      - npm run lint

      - echo "Running tests..."
      - npm run test

      - echo "Packaging..."
      - npm run build

      - echo "Compiling API template..."
      - mustache aws.json templates/api.yml > artifacts/api.yml

      - echo "Compiling Cloudformation (Bucket $S3_BUCKET)..."
      - "aws cloudformation package --template-file .aws/service.yml --s3-prefix build --s3-bucket $S3_BUCKET --output-template-file artifacts/template.yml"

      - echo "Moving Deployment Configuration files..."
      - "cp .aws/.config/* artifacts/"

  post_build:
    commands:
      - echo "Listing artifacts..."
      - "ls -lR artifacts/"

artifacts:
  type: zip
  discard-paths: yes
  files:
    - artifacts/**/*
